name: Laravel

on:
  push:
    branches: [ "develop" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: testci
      run: echo "hello world !"
    - name: test step 2
      run: echo "hello world 123123123123 !"
